version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "ZshanUmar"
github_repo = "sam-app"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::077736414234:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-iwuueAy9dVpG"
cloudformation_execution_role = "arn:aws:iam::077736414234:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-qoirqu4ZkQrP"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-nhr3ej70swvd"
image_repository = ""
region = "ap-southeast-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::077736414234:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-2PYI85MZzbVP"
cloudformation_execution_role = "arn:aws:iam::077736414234:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-xecGQgHYJzZt"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-gz7w6jis4je5"
image_repository = ""
region = "ap-southeast-1"
